### ISSUE TITLE
Riegeli is incompatible with --incompatible_load_proto_rules_from_bzl

### ISSUE THREAD

**Issue by shahms** [google/riegeli#6]
This should be pretty straightfoward to fix, quoting from https://github.com/kythe/kythe/issues/4264 -- the bug Bazel filed against us (Kythe):

> The Bazel team is in progress of migrating the native Protobuf rules to Starlark. As a first step towards this goal, starting with Bazel 3.0, all Protobuf rules will require explicit load statements.
> 
> You can use the following buildifier command to apply most of the required migrations for you:
> 
> buildifier --lint=fix --warnings=native-proto $(find . -name "BUILD" -o -name "BUILD.bazel" -o -name "*.bzl")
> For further information, see bazelbuild/bazel#8922 or ping me.

**Comment by QrczakMK** [comment]
Thank you. I am working on this.
