### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Bingo20** [google/riegeli#9]
I run command:  bazel build //python:build_pip_package

and get the following errors:

ERROR: /home/libin/Downloads/riegeli-master/riegeli/bytes/BUILD:438:1: C++ compilation of rule '//riegeli/bytes:cord_writer' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 23 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
riegeli/bytes/cord_writer.cc:37:31: error: conflicting declaration 'constexpr const int riegeli::CordWriterBase::kShortBufferSize'
 constexpr int CordWriterBase::kShortBufferSize;
                               ^
In file included from riegeli/bytes/cord_writer.cc:15:0:
./riegeli/bytes/cord_writer.h:123:27: note: previous declaration as 'constexpr const size_t riegeli::CordWriterBase::kShortBufferSize'
   static constexpr size_t kShortBufferSize = 64;
                           ^
riegeli/bytes/cord_writer.cc:37:31: error: declaration of 'constexpr const size_t riegeli::CordWriterBase::kShortBufferSize' outside of class is not definition [-fpermissive]
 constexpr int CordWriterBase::kShortBufferSize;
                               ^
Target //python:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 91.754s, Critical Path: 12.92s
INFO: 479 processes: 479 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by QrczakMK** [comment]
I am sorry. This was fixed in https://github.com/google/riegeli/commit/16b33996293079591dc99573c0edf98ef008fd13.
